import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/mycomp/Footer";
import { CartProvider } from "../hooks/CartProvider";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Rental Car",
  description: "Generated by console.log",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} ${robotoMono.variable} antialiased`}>
         <CartProvider>
          {children}
         </CartProvider>
        <Footer />
      </body>
    </html>
  );
}
